#!/usr/bin/env python3
"""Generate the claude-flags quick-ref HTML with live env var values.

Usage: python3 claude-flags-generator.py > /tmp/quick-ref.html

Reads the static HTML template from claude-flags-template.html,
scans current env var values, and injects value badges into env var entries.
"""

import os
import re
import sys
from html import escape
from pathlib import Path

SENSITIVE_PATTERNS = ['API_KEY', 'TOKEN', 'SECRET', 'PASSPHRASE', '_KEY', '_CERT', 'BEARER']

ENV_VARS = [
    'ANTHROPIC_API_KEY','ANTHROPIC_AUTH_TOKEN','ANTHROPIC_BASE_URL','ANTHROPIC_BEDROCK_BASE_URL',
    'ANTHROPIC_VERTEX_BASE_URL','ANTHROPIC_VERTEX_PROJECT_ID','ANTHROPIC_FOUNDRY_API_KEY',
    'ANTHROPIC_FOUNDRY_BASE_URL','ANTHROPIC_FOUNDRY_RESOURCE','AWS_BEARER_TOKEN_BEDROCK',
    'CLAUDE_CODE_OAUTH_TOKEN','CLAUDE_CODE_OAUTH_REFRESH_TOKEN','CLAUDE_CODE_OAUTH_SCOPES',
    'ANTHROPIC_MODEL','ANTHROPIC_DEFAULT_OPUS_MODEL','ANTHROPIC_DEFAULT_SONNET_MODEL',
    'ANTHROPIC_DEFAULT_HAIKU_MODEL','ANTHROPIC_CUSTOM_MODEL_OPTION','ANTHROPIC_CUSTOM_MODEL_OPTION_NAME',
    'ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION','CLAUDE_CODE_SUBAGENT_MODEL',
    'ANTHROPIC_SMALL_FAST_MODEL','ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION',
    'ANTHROPIC_BETAS','ANTHROPIC_CUSTOM_HEADERS','API_TIMEOUT_MS','CLAUDE_CODE_MAX_RETRIES',
    'CLAUDE_CODE_MAX_OUTPUT_TOKENS','MAX_THINKING_TOKENS','CLAUDE_CODE_DISABLE_THINKING',
    'CLAUDE_CODE_EFFORT_LEVEL','CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING',
    'BASH_DEFAULT_TIMEOUT_MS','BASH_MAX_TIMEOUT_MS','BASH_MAX_OUTPUT_LENGTH',
    'CLAUDE_CODE_SHELL','CLAUDE_CODE_SHELL_PREFIX','CLAUDE_CODE_GIT_BASH_PATH',
    'CLAUDE_CODE_USE_POWERSHELL_TOOL','CLAUDE_CODE_GLOB_HIDDEN','CLAUDE_CODE_GLOB_NO_IGNORE',
    'CLAUDE_CODE_GLOB_TIMEOUT_SECONDS','CLAUDE_CODE_FILE_READ_MAX_OUTPUT_TOKENS',
    'CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY',
    'CLAUDE_CODE_DISABLE_AUTO_MEMORY','CLAUDE_CODE_DISABLE_CLAUDE_MDS',
    'CLAUDE_CODE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD','DISABLE_AUTO_COMPACT','DISABLE_COMPACT',
    'CLAUDE_AUTOCOMPACT_PCT_OVERRIDE','CLAUDE_CODE_AUTO_COMPACT_WINDOW',
    'CLAUDE_CONFIG_DIR','CLAUDE_CODE_TMPDIR','CLAUDE_CODE_PLUGIN_CACHE_DIR','CLAUDE_CODE_PLUGIN_SEED_DIR',
    'CLAUDE_CODE_DISABLE_FILE_CHECKPOINTING','CLAUDE_BASH_MAINTAIN_PROJECT_WORKING_DIR','CLAUDE_ENV_FILE',
    'CLAUDE_CODE_AUTO_CONNECT_IDE','CLAUDE_CODE_IDE_HOST_OVERRIDE','CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL',
    'CLAUDE_CODE_IDE_SKIP_VALID_CHECK',
    'CLAUDE_CODE_DISABLE_BACKGROUND_TASKS','CLAUDE_AUTO_BACKGROUND_TASKS','CLAUDE_CODE_DISABLE_CRON',
    'CLAUDE_CODE_NO_FLICKER','CLAUDE_CODE_SCROLL_SPEED','CLAUDE_CODE_DISABLE_MOUSE',
    'CLAUDE_CODE_DISABLE_TERMINAL_TITLE','CLAUDE_CODE_SYNTAX_HIGHLIGHT','CLAUDE_CODE_ACCESSIBILITY',
    'CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION',
    'CLAUDE_CODE_CLIENT_CERT','CLAUDE_CODE_CLIENT_KEY','CLAUDE_CODE_CLIENT_KEY_PASSPHRASE',
    'CLAUDE_CODE_SUBPROCESS_ENV_SCRUB','CLAUDE_CODE_PROXY_RESOLVES_HOSTS',
    'CLAUDE_CODE_SKIP_BEDROCK_AUTH','CLAUDE_CODE_SKIP_VERTEX_AUTH','CLAUDE_CODE_SKIP_FOUNDRY_AUTH',
    'HTTP_PROXY','HTTPS_PROXY','NO_PROXY',
    'CLAUDE_CODE_DEBUG_LOGS_DIR','CLAUDE_CODE_DEBUG_LOG_LEVEL','CLAUDECODE',
    'CLAUDE_ENABLE_STREAM_WATCHDOG','CLAUDE_STREAM_IDLE_TIMEOUT_MS',
    'CLAUDE_CODE_DISABLE_1M_CONTEXT','CLAUDE_CODE_DISABLE_FAST_MODE','CLAUDE_CODE_DISABLE_ATTACHMENTS',
    'CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS','CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK',
    'CLAUDE_CODE_ENABLE_FINE_GRAINED_TOOL_STREAMING','CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS',
    'CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS','CLAUDE_CODE_ENABLE_TASKS',
    'DISABLE_INTERLEAVED_THINKING','DISABLE_PROMPT_CACHING','DISABLE_PROMPT_CACHING_OPUS',
    'DISABLE_PROMPT_CACHING_SONNET','DISABLE_PROMPT_CACHING_HAIKU',
    'ENABLE_CLAUDEAI_MCP_SERVERS','ENABLE_TOOL_SEARCH',
    'DISABLE_TELEMETRY','DISABLE_ERROR_REPORTING','DISABLE_AUTOUPDATER',
    'FORCE_AUTOUPDATE_PLUGINS','CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY',
    'DISABLE_DOCTOR_COMMAND','DISABLE_LOGIN_COMMAND','DISABLE_LOGOUT_COMMAND',
    'DISABLE_FEEDBACK_COMMAND','DISABLE_INSTALLATION_CHECKS','DISABLE_INSTALL_GITHUB_APP_COMMAND',
    'DISABLE_UPGRADE_COMMAND','DISABLE_EXTRA_USAGE_COMMAND','DISABLE_COST_WARNINGS',
    'DISABLE_OFFICIAL_MARKETPLACE_AUTOINSTALL',
    'CLAUDE_CODE_SIMPLE','CLAUDE_CODE_NEW_INIT','CLAUDE_CODE_EXIT_AFTER_STOP_DELAY',
    'CLAUDE_CODE_RESUME_INTERRUPTED_TURN','CLAUDE_CODE_SYNC_PLUGIN_INSTALL',
    'CLAUDE_CODE_SYNC_PLUGIN_INSTALL_TIMEOUT_MS','CLAUDE_CODE_PLUGIN_GIT_TIMEOUT_MS',
    'CLAUDE_CODE_TASK_LIST_ID','CLAUDE_CODE_TEAM_NAME','CLAUDE_CODE_SESSIONEND_HOOKS_TIMEOUT_MS',
    'CLAUDE_CODE_API_KEY_HELPER_TTL_MS','CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC',
    'FALLBACK_FOR_ALL_PRIMARY_MODELS',
    'CLAUDE_AGENT_SDK_DISABLE_BUILTIN_AGENTS','CLAUDE_AGENT_SDK_MCP_NO_PREFIX',
    'CLAUDE_CODE_ENABLE_TELEMETRY','CLAUDE_CODE_OTEL_FLUSH_TIMEOUT_MS',
    'CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS','CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS',
]


def is_sensitive(var_name):
    return any(p in var_name for p in SENSITIVE_PATTERNS)


def get_badge(var_name):
    val = os.environ.get(var_name)
    if val is None:
        return '<span class="env-val unset">not set</span>'
    if is_sensitive(var_name) and val:
        if len(val) > 8:
            masked = val[:4] + '...' + val[-4:]
        else:
            masked = '****'
        return f'<span class="env-val masked">{escape(masked)}</span>'
    return f'<span class="env-val set">= {escape(val)}</span>'


def main():
    template_path = Path(__file__).parent / 'claude-flags-template.html'
    html = template_path.read_text()

    # Find where env vars section starts
    env_start = html.find('<h2>Environment Variables')
    if env_start == -1:
        print(html)
        return

    for var_name in ENV_VARS:
        pattern = f'<code>{re.escape(var_name)}</code>'
        idx = html.find(f'<code>{var_name}</code>', env_start)
        if idx == -1:
            continue
        badge = get_badge(var_name)
        old = f'<code>{var_name}</code>'
        new = f'<code>{var_name}</code>{badge}'
        before = html[:idx]
        after = html[idx:]
        after = after.replace(old, new, 1)
        html = before + after

    print(html)


if __name__ == '__main__':
    main()
